version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:16.14.2

commands:
  setup_yarn:
    description: "Setup yarn with cache"
    steps:
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    executors: default
    steps:
      - checkout
      - setup_yarn
      - run: yarn test
  type-check:
    executors: default
    steps:
      - checkout
      - setup_yarn
      - run: yarn type-check
  test-storybook:
    executors: default
    steps:
      - checkout
      - setup_yarn
      - run: yarn type-check
      - run:
          name: install playwright browsers and dependencies
          command: npx playwright install --with-deps
      - run: yarn test-storybook:ci
workflows:
  test:
    jobs:
      - test
      - type-check
      - test-storybook