version: 2.1
orbs:
  node: circleci/node@16.14.2
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test