version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: yarn
      - run: yarn test
workflows:
  test:
    jobs:
      - test